[Configuration]
BasedOn=..\Engine\Config\BaseEngine.ini

[URL]
MapExt=upk
EXEName=BmGame.exe
DebugEXEName=DEBUG-BmGame.exe
GameName=Batman
GameNameShort=Bm
Map=None.umap

[Core.System]
+Paths=..\..\BmGame\Content
+Paths=..\..\BmGame\__Trashcan
+Paths=..\..\BmGame\CookedPCConsole
+LocalizationPaths=..\..\BmGame\Localization
SavePath=..\..\BmGame\Save
+Suppress=DevScript
+Suppress=DevAnim
-Suppress=Init
-Suppress=DevShaders
+Extensions=upk
+Extensions=umap
SeekFreePCPaths=..\BmGame\CookedPCConsole
SeekFreePCExtensions=upk
UseTextureFileCache=TRUE

[Engine.PackagesToAlwaysCook]
+Package=Boot
+Package=BatEntry
+Package=Frontend
+Package=DebugFrontend
; Why have we marked these two for seek free loading??
+SeekFreePackage=OnlineSubsystemLive
+SeekFreePackage=OnlineSubsystemNP
+SeekFreePackage=OnlineSubsystemSteamworks

[DevOptions.Shaders]
bAllowMultiThreadedShaderCompile=True

[Engine.ISVHacks]
bInitializeShadersOnDemand=True
DisableATITextureFilterOptimizationChecks=True
UseMinimalNVIDIADriverShaderOptimization=True
PumpWindowMessagesWhenRenderThreadStalled=False

[UnrealEd.EditorEngine]
EditPackagesOutPath=..\..\BmGame\Script
FRScriptOutputPath=..\..\BmGame\ScriptFinalRelease
-EditPackages=OnlineSubsystemLive
-EditPackages=OnlineSubsystemSteamworks
-EditPackages=OnlineSubsystemGameSpy
+EditPackages=OnlineSubsystemGameCenter
+EditPackages=BmGame
AutoSaveDir=..\..\BmGame\Autosaves
InEditorGameURLOptions=

[Engine.Engine]
bEnableColorClear=TRUE
DefaultOnlineSubsystemName=OnlineSubsystemPC.OnlineSubsystemPC
FacebookIntegrationClassName=WinDrv.FacebookWindows
ConsoleClassName=Engine.Console
TinyFontName=EngineFonts.TinyFont
SmallFontName=EngineFonts.SmallFont
MediumFontName=EngineFonts.SmallFont
LargeFontName=EngineFonts.SmallFont
SubtitleFontName=EngineFonts.SmallFont
DefaultPostProcessName=PostProcess.PostProcess

[Engine.StartupPackages]
bSerializeStartupPackagesFromMemory=TRUE
bFullyCompressStartupPackages=FALSE
-Package=SoundModes
-Package=SoundClassesAndModes
-Package=DefaultUISkin
-Package=EngineFonts
+Package=_Engine
+Package=_BmGame
# Contains PostProcess
+Package=Startup

[Engine.PackagesToAlwaysCook]
+Package=Boot
+Package=BatEntry
+Package=Frontend
+Package=DebugFrontend

[Engine.Client]
DisplayGamma=2.0
DisplayGammaMin=1.3
DisplayGammaMax=3.3
DisplayGammaReferenceBrightness=0.67f;

[Engine.DataStoreClient]
!GlobalDataStoreClasses=ClearArray
!PlayerDataStoreClassNames=ClearArray

[SystemSettings]
ResX=1280
ResY=720
Reflections=True

DisableLightEnvironments=False
;@Rock - JN - whether or not to  the forcing of dynamic lights/shadows
DisableForceDynamicLighting=False
;@Rock - JoelS: changing default actor shadow settings to more optimised version:
MaxShadowResolution=1120
ShadowFadeResolution=32
MinShadowResolution=16
ShadowTexelsPerPixel=1.0
ShadowDepthBias=0.012
;@Rock - JoelS: Stick the shadow more directly underneath the actor, weighted by 50%:
AmbientShadowColor=(R=0.0,G=0.0,B=0.0)
MinShadowAngle=0.0

DetailMode=2
DisableSphericalHarmonicLights=False
bEnableForegroundShadowsOnWorld=False
bEnableForegroundSelfShadowing=False
ShadowFadeExponent=1
TEXTUREGROUP_LightAndShadowMap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_Character=(MinLODSize=256,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_CharacterNormalMap=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_CharacterSpecular=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_CharacterSpecPower=(MinLODSize=128,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_Effects=(MinLODSize=128,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=point)
TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_Skybox=(MinLODSize=256,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_UI=(MinLODSize=1024,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_Vehicle=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_VehicleNormalMap=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_VehicleSpecular=(MinLODSize=128,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_Weapon=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_WeaponNormalMap=(MinLODSize=128,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_WeaponSpecular=(MinLODSize=128,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_World_Low=(MinLODSize=128,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_World=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_WorldNormalMap=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_WorldSpecular=(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_World_Hi=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_WorldNormalMap_Hi =(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_WorldSpecular_Hi =(MinLODSize=128,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)

[Windows.StandardUser]
MyDocumentsSubDirName=UnrealEngine3

[TextureStreaming]
MinEvictSize=12
FudgeFactorIncreaseRateOfChange=0.5
FudgeFactorDecreaseRateOfChange=-0.4
MinRequestedMipsToConsider=11
MinTimeToGuaranteeMinMipCount=2
MaxTimeToGuaranteeMinMipCount=12
PoolSize=1024
HysteresisLimit=15
DropMipLevelsLimit=12
StopIncreasingLimit=9
StopStreamingLimit=6
MinFudgeFactor=0.5
UseTextureFileCache=True

[ConfigCoalesceFilter]
FilterOut=OnlineSubsystemGameSpy.int

[FullScreenMovie]
;Startup is already playing, so just add a looping movie to the end
;+StartupMovies=Loading
;Allow for skipping the Startup movie after engine has loaded
+SkippableMovies=Startup
+LoadMapMovies=Loading
bShouldStopMovieAtEndOfLoadMap=TRUE
DefaultSplashTime=4.0
SplashTime_CastleLoad=20.0

[FacebookIntegration]
AppID=153031704752474
