/*=============================================================================
	BasePassCommon.usf: Base pass definitions used by both vertex and pixel shader
	Copyright 1998-2011 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#if XBOX || PS3
	#if ENABLE_A_PLUS_THREE_D_LIGHT
		#define SUPPORTS_MULTITYPE_BASEPASS_LIGHT	0
	#else
		#define SUPPORTS_MULTITYPE_BASEPASS_LIGHT	1
	#endif
#else
	#define SUPPORTS_MULTITYPE_BASEPASS_LIGHT	0
#endif

#define V_INPUT_CAMERAVECTOR		TEXCOORD6
#define V_INPUT_SKYVECTOR			TEXCOORD7
#define V_INPUT_TANGENTLIGHTVECTOR	TEXCOORD8
#define V_INPUT_WORLDLIGHTVECTOR	TEXCOORD9
#define V_INPUT_TANGENTLIGHTVECTOR0	TEXCOORD3
#define V_INPUT_TANGENTLIGHTVECTOR1	TEXCOORD8
#define V_INPUT_TANGENTLIGHTVECTOR2	TEXCOORD9

#define TANGENT_LIGHT_VECTOR_DEFINED 0

// NVCHANGE_BEGIN_RS: Adding DX11 Multi-View Soft Shadows
#include "MVSSCommon.usf"
// NVCHANGE_END_RS: Adding DX11 Multi-View Soft Shadows

struct FSharedBasePassInterpolants
{
	#if VERTEX_LIGHTMAP
		float3 LightMapA	: TEXCOORD2;
		float3 LightMapB	: TEXCOORD3;
		#if NEEDS_BASEPASS_FOGGING
			float4 VertexFog	: TEXCOORD4;
		#endif
	#else
		#if SIMPLE_VERTEX_LIGHTMAP
			float3 LightMapA		: TEXCOORD2;
		#endif
		//for texture-lightmapped translucency we can pass the vertex fog in its own interpolator
		#if NEEDS_BASEPASS_FOGGING
			#if (ENABLE_DIRECTIONAL_LIGHT || ENABLE_MULTITYPE_BASEPASS_LIGHT) && !MATERIAL_LIGHTINGMODEL_UNLIT
				#undef TANGENT_LIGHT_VECTOR_DEFINED
				#define TANGENT_LIGHT_VECTOR_DEFINED 1
				float4 TangentLightVector	: TEXCOORD3;
			#endif
			float4 VertexFog		: TEXCOORD4;
		#elif ENABLE_DIRECTIONAL_LIGHT || ENABLE_MULTITYPE_BASEPASS_LIGHT
			#undef TANGENT_LIGHT_VECTOR_DEFINED
			#define TANGENT_LIGHT_VECTOR_DEFINED 1
			float4 TangentLightVector	: TEXCOORD4;
		#endif
	#endif

	#if !PC_D3D
		float4 PixelPosition	: TEXCOORD5;
	#endif

	#if PER_PIXEL_CAMERA_VECTOR || !ROCK_STRIP_VERTEX_COLOUR
		// If we're computing the camera vector per-pixel, then we don't need to transport it to the pixel
		// shader in an interpolator.  Instead, we'll use this slot for storing vertex color, which we
		// normally wouldn't have space for (due to tangent -> world matrix for WORLD_COORDS=1)
		float4 CameraVectorOrVertexColor : V_INPUT_CAMERAVECTOR;
	#endif

	#if !MATERIAL_LIGHTINGMODEL_UNLIT && !ENABLE_A_PLUS_THREE_D_LIGHT
		#if ENABLE_TRANSLUCENCY_DOF
			// Translucency DoF blur amount is stored in SkyVector.w
			float4 SkyVector	: V_INPUT_SKYVECTOR;
			#define TranslucencyDoFBlur SkyVector.w
		#else
			float3 SkyVector	: V_INPUT_SKYVECTOR;
		#endif
	#else
		#if ENABLE_TRANSLUCENCY_DOF
		float TranslucencyDoFBlur : V_INPUT_SKYVECTOR;
		#endif		
	#endif

	// If TangentLightVector couldn't be allocated and ENABLE_DIRECTIONAL_LIGHT || ENABLE_MULTITYPE_BASEPASS_LIGHT is enabled, 
	// Use one of the extended interpolators that PC SM3 doesn't support
	#if (ENABLE_DIRECTIONAL_LIGHT || ENABLE_MULTITYPE_BASEPASS_LIGHT) && !TANGENT_LIGHT_VECTOR_DEFINED && SUPPORTS_MULTITYPE_BASEPASS_LIGHT
		#undef TANGENT_LIGHT_VECTOR_DEFINED
		#define TANGENT_LIGHT_VECTOR_DEFINED 1
		float4 TangentLightVector : V_INPUT_TANGENTLIGHTVECTOR;
	#endif

	#if ENABLE_MULTITYPE_BASEPASS_LIGHT
		float3 WorldLightVector : V_INPUT_WORLDLIGHTVECTOR;
	#endif

	#if ENABLE_A_PLUS_THREE_D_LIGHT
		float4 TangentLightVector0 : V_INPUT_TANGENTLIGHTVECTOR0;
		float4 TangentLightVector1 : V_INPUT_TANGENTLIGHTVECTOR1;
		float4 TangentLightVector2 : V_INPUT_TANGENTLIGHTVECTOR2;
	#endif
};

#if PC_D3D

/** Interpolants passed from the vertex shader to the pixel shader. */
struct FBasePassInterpolantsVSToPS : FSharedBasePassInterpolants
{
	float4 PixelPosition	: TEXCOORD5;

	// NVCHANGE_BEGIN_RS: Adding DX11 Multi-View Soft Shadows
	#if ENABLE_MVSS
	FMVSSInterpolants MVSSInterpolants;
	#endif
	// NVCHANGE_END_RS: Adding DX11 Multi-View Soft Shadows
};

/** Interpolants passed from the vertex shader to the domain shader. */
struct FBasePassInterpolantsVSToDS : FSharedBasePassInterpolants
{
};

#else

// Only the PC shader compiler supports HLSL inheritance
#define FBasePassInterpolantsVSToPS FSharedBasePassInterpolants

#endif

