/*=============================================================================
	BasePassPixelShader.usf: Base pass pixel shader
	Copyright 1998-2011 Epic Games, Inc. All Rights Reserved.
=============================================================================*/
//@Rock - JG: Character Lighting Improvements. 
#include "Common.usf"

//@Rock - JG: Character Lighting Improvements. 
#undef NEEDS_LIGHTMAP_COORDINATE
#define NEEDS_LIGHTMAP_COORDINATE	(TEXTURE_LIGHTMAP || SIMPLE_TEXTURE_LIGHTMAP || STATICLIGHTING_TEXTUREMASK)
#undef NEEDS_SHADOWMAP_COORDINATE
#define NEEDS_SHADOWMAP_COORDINATE	STATICLIGHTING_TEXTUREMASK

/* If simple lighting is enabled then the base pass shader will just be Diffuse * LightMap + Emissive */
#define SIMPLE_LIGHTING				((SIMPLE_VERTEX_LIGHTMAP || SIMPLE_TEXTURE_LIGHTMAP) && !MATERIAL_LIGHTINGMODEL_CUSTOM)

#undef NEEDS_BASEPASS_FOGGING //@Rock - JG:Fixed warning
#define NEEDS_BASEPASS_FOGGING		(MATERIALBLENDING_TRANSLUCENT || MATERIALBLENDING_ADDITIVE) && !(DECAL_FACTORY && GPUSKIN_DECAL)

// SH lighting requires a TangentToWorld matrix.
#if ENABLE_SH_LIGHT
	#undef WORLD_COORDS
	#define WORLD_COORDS 1
#endif

// World position is needed when fading based on distance between dynamic and precomputed shadows
#if DYNAMICALLY_SHADOWED_BASEPASS_LIGHT
	#undef WORLD_POS
	#define WORLD_POS 1
#endif

#include "Material.usf"
#include "VertexFactory.usf"
#include "DynamicLightingCommon.usf"

#if ENABLE_SH_LIGHT
	#include "SphericalHarmonicCommon.usf"
#endif

#if ENABLE_A_PLUS_THREE_D_LIGHT  //@Rock - JG: Improved character lighting
	#include "AmbientPlus3DirectionalPixelCommon.usf"
#endif 

#include "BasePassCommon.usf"

/** 1 if this object has MotionBlurScale set to enable motionblur, and 0 if disabled */
float MotionBlurMask;

#if SUPPORTS_MULTITYPE_BASEPASS_LIGHT
	/** Whether the dynamic light being rendered is a directional light. */
	bool bDynamicDirectionalLight;
	/** Whether the dynamic light being rendered is a spot light. */
	bool bDynamicSpotLight;
	/** RGB contains a mask to be applied to per-object shadow factors, A is 1 if the object is unshadowed. */
	float4 LightChannelMask;
#endif

/** Spot light parameters. */
float3	SpotDirection;
float2	SpotAngles;

//@ROCK - BW: Changed to be constants as we don't change these dynamically and have compiled out this feature on the ROCK_DLEC_USE_SH define
#if ENABLE_SKY_LIGHT
#define UpperSkyColor 0
#define LowerSkyColor 0
#endif

// SkyFactor and AmbientColor are constants if we assume SHOW_Lighting to be always set. We make the assumption that on console 
// performance is more important than being able to toggle this flag and therefore use special shortcut.
#if XBOX || PS3
	static const half3 AmbientColor = 0;
	static const half SkyFactor = 1;
#else
	half4 AmbientColorAndSkyFactor;
	static const half3 AmbientColor = AmbientColorAndSkyFactor.rgb;
	static const half SkyFactor = AmbientColorAndSkyFactor.a;
#endif

//@Rock - JG: Character Lighting Improvements. 
#if !ENABLE_A_PLUS_THREE_D_LIGHT
#if TEXTURE_LIGHTMAP || SIMPLE_TEXTURE_LIGHTMAP
	// Directional lightmaps use 3 samplers here, and ShadowTexture uses one more, and if DYNAMICALLY_SHADOWED_BASEPASS_LIGHT is defined, another will be used for that,
	// So the most a material with static lighting can use is 11.  This is enforced by the material compiler through MAX_ME_STATICLIGHTING_PIXELSHADER_SAMPLERS,
	// Dynamically lit materials are enforced through MAX_ME_DYNAMICLIGHTING_PIXELSHADER_SAMPLERS.
	sampler2D LightMapTextures[NUM_LIGHTMAP_COEFFICIENTS];

	// The light-map scale array is a set of float4s so it can be set as a contiguous chunk regardless of platform shader constant alignment.
	float4 LightMapScale[NUM_LIGHTMAP_COEFFICIENTS];

		#if MODULATED_SHADOWMAP
			half4 ModShadowColor;
		#endif
	#endif
#endif

#if IMAGE_BASED_REFLECTIONS && SM5_PROFILE

/** Populates WorldNormal and SpecularColorAndPower. */
void GetImageReflectionOutputs(FMaterialPixelParameters MaterialParameters, out float4 WorldNormal, out float4 SpecularColorAndPower)
{
	// Make the normal less bumpy - needed to reduce image reflection aliasing
	//@todo - move this into the deferred pass somehow so that other deferred passes can get the original normal
	float3 DampenedTangentNormal = normalize(MaterialParameters.TangentNormal * float3(1, 1, 10));
	// Transform the per pixel normal into world space
	WorldNormal = float4(TransformTangentVectorToWorld(MaterialParameters.TangentToWorld, DampenedTangentNormal), 0);

	float OriginalSpecularPower = GetMaterialSpecularPower(MaterialParameters);
	float3 WorldSurfaceNormal = MaterialParameters.TangentToWorld[2];
	float2 DerivativeLengths = float2(length(ddx(WorldSurfaceNormal)), length(ddy(WorldSurfaceNormal)));
	// Heuristic that measures how quickly the surface normal is changing in screen space
	float SurfaceNormalDeviation = saturate(max(DerivativeLengths.x, DerivativeLengths.y) * 10.0f);
	// Lower the specular power of pixels whose normal is changing quickly in screen space, this hides a lot of specular and image reflection aliasing
	SpecularColorAndPower = float4(GetMaterialSpecularColor(MaterialParameters), lerp(OriginalSpecularPower, 1, SurfaceNormalDeviation));
}

#endif

void Main(
	FVertexFactoryInterpolantsVSToPS Interpolants,
	FBasePassInterpolantsVSToPS BasePassInterpolants,
	OPTIONAL_PixelShaderScreenPosition
	OPTIONAL_FacingSign
	OPTIONAL_PixelShaderCoverageInputOutput
	out float4 OutColor		: COLOR0
#if ENABLE_TRANSLUCENCY_DOF && XBOX
	,out float4 OutTranslucencyDoFBlur : COLOR1
#endif
#if PC_D3D
	,out float4 OutSubsurfaceInscattering : COLOR1
	,out float4 OutSubsurfaceScatteringAttenuation : COLOR2
#endif
#if IMAGE_BASED_REFLECTIONS && SM5_PROFILE
	,out float4 OutWorldNormal : COLOR3 
	,out float4 OutSpecularColorAndPower : COLOR4
#endif
	)
{
	FMaterialPixelParameters MaterialParameters = GetMaterialPixelParameters(Interpolants);

#if MATERIAL_DECAL && XBOX
	float3 ClipDecal = GetMaterialClippingDecal(MaterialParameters);
	float AttenDecal = GetMaterialAttenuationDecal(MaterialParameters);
	IFALL
	if( ClipDecal.x <= 0 ||
		ClipDecal.y <= 0 || 
		ClipDecal.z <= 0 ||
		AttenDecal <= 0 )
	{
		#if MATERIALBLENDING_MODULATE
			OutColor = float4(1,1,1,1);
		#else
			OutColor = float4(0,0,0,0);
		#endif
	}
	else
	{
#endif

 //@Rock - JG: Improved character lighting. 
	#if ENABLE_A_PLUS_THREE_D_LIGHT
		float4 TangentLightVector = BasePassInterpolants.TangentLightVector0;
	#else
	#if TANGENT_LIGHT_VECTOR_DEFINED
		float4 TangentLightVector = BasePassInterpolants.TangentLightVector;
	#else
		float4 TangentLightVector = float4(0,0,1,1);
	#endif
	#endif 

	//Don't flip the normal for backfaces of two-sided materials used with this shader.
	//As a result, the backfaces will have the same lighting as the frontfaces, instead of being mostly black.
#if PER_PIXEL_CAMERA_VECTOR || !ROCK_STRIP_VERTEX_COLOUR //@Rock - JG: LOD Shader Simplification. 
	CalcMaterialParameters(MaterialParameters,FacingSign,BasePassInterpolants.CameraVectorOrVertexColor,BasePassInterpolants.PixelPosition,TangentLightVector.xyz,
		//@Rock - JoelS: add ability to override the two sided lighting flag.
		#if MATERIAL_TWOSIDED && DISABLE_TWOSIDED_LIGHTING
			false
		#else
			true
		#endif //DISABLE_TWOSIDED_LIGHTING		
		);
#else
	CalcMaterialParameters(MaterialParameters,FacingSign,float4(0,0,0,0),BasePassInterpolants.PixelPosition,TangentLightVector.xyz,
		//@Rock - JoelS: add ability to override the two sided lighting flag.
		#if MATERIAL_TWOSIDED && DISABLE_TWOSIDED_LIGHTING
			false
		#else
			true
		#endif //DISABLE_TWOSIDED_LIGHTING		
		);		
#endif 
	//Clip if the blend mode requires it.
	GetMaterialCoverageAndClipping(MaterialParameters,PixelShaderScreenPosition,InCoverage,OutCoverage);

	// Store the result of GetMaterialDiffuseColor in a local variable and reuse that instead of calling the function multiple times.
	// This drastically reduces compile time on Xbox 360 with a complex diffuse material input and can improve the compiled result too.
	float3 DiffuseColor = GetMaterialDiffuseColor(MaterialParameters);
	#if MATERIAL_LIGHTINGMODEL_CUSTOM
		float3 CustomLightingDiffuse = GetMaterialCustomLightingDiffuse(MaterialParameters);
	#else
		float3 CustomLightingDiffuse = float3(0,0,0);
	#endif
	float3 SpecularColor = 0;
		#if !(IMAGE_BASED_REFLECTIONS && SM5_PROFILE)
			// Image based reflections replace analytical lightmap specular
			SpecularColor = GetMaterialSpecularColor(MaterialParameters);
		#endif

	half3 Emissive = GetMaterialEmissive(MaterialParameters);
	half3 Color = Emissive;
	half3 IncidentLighting = 0;

	#if !MATERIAL_LIGHTINGMODEL_UNLIT
		#if !SIMPLE_LIGHTING

			// Lightmap basis vectors used by directional lightmaps
			// These must match the LightMapBasis in StaticLightingLegacyCode.cpp and LightingSystem.h in Lightmass
			// The matrix is transposed to workaround a Cg compiler bug (see cl 172693), and is compensated for by reversing mul order
			static const half3x3 LightMapBasis = half3x3(
				half3(	0.0f,					-1.0f / sqrt(2.0f),			+1.0f / sqrt(2.0f)),
				half3(	sqrt(6.0f) / 3.0f,		-1.0f / sqrt(6.0f),			-1.0f / sqrt(6.0f)),
				half3(	1.0f / sqrt(3.0f),		1.0f / sqrt(3.0f),			1.0f / sqrt(3.0f))
				);

#if DECAL_FACTORY
			// for decals the normal and reflection vector are transformed ouf of the projected decal frame 
			// and back into the original vertex basis.  Interpolants.TangentToWorld2 contains the 2x2 rotation
			half4 TangentToWorld2 = UnpackColor4( Interpolants.TangentToWorld2 );

			half MatNormalX = dot( MaterialParameters.TangentNormal.xy, TangentToWorld2.xy );
			half MatNormalY = dot( MaterialParameters.TangentNormal.xy, TangentToWorld2.zw );
			half3 MatNormal = half3(MatNormalX,MatNormalY,MaterialParameters.TangentNormal.z);

			half MatReflectX = dot( MaterialParameters.TangentReflectionVector.xy, TangentToWorld2.xy );
			half MatReflectY = dot( MaterialParameters.TangentReflectionVector.xy, TangentToWorld2.zw );
			half3 MatReflect = half3(MatReflectX,MatReflectY,MaterialParameters.TangentReflectionVector.z);

			half3 LightMapNormal = mul(MatNormal,LightMapBasis);
			half3 LightMapReflectionVector = mul(MatReflect,LightMapBasis);

#else
			// Transform the per-pixel normal into the coordinate space defined by the lightmap basis
			// Each component of LightMapNormal is the dot product of the per-pixel normal with the corresponding lightmap basis vector
			// So for the interpolated vertex normal which is (0,0,1) in tangent space, each component would be 1 / sqrt(3) == .577f
			half3 LightMapNormal = mul(MaterialParameters.TangentNormal,LightMapBasis);
			half3 LightMapReflectionVector = mul(MaterialParameters.TangentReflectionVector,LightMapBasis);
#endif

			half3 TwoSidedLightingMask = GetMaterialTwoSidedLightingMask(MaterialParameters);
			#if MATERIAL_LIGHTINGMODEL_NONDIRECTIONAL
				TwoSidedLightingMask = 1;
			#endif

//@RockIntJan10 - Took Joel's changes, start
			//@Rock - JoelS: moving functions into Common.usf, and optomising:
			#if SPECULAR_HAS_FRESNEL
				half3 EyeVector			= mul(MaterialParameters.TangentCameraVector, LightMapBasis);
				half FresnelExponential = pow(1 - saturate(dot(mul( MaterialParameters.TangentLightVector, LightMapBasis),EyeVector) * 0.5 + 0.5), GetMaterialFresnelPower(MaterialParameters));
				// interpolate between FresnelMin and 1.0 by exponential term
				half Fresnel = FresnelExponential + GetMaterialFresnelMin(MaterialParameters) * (1.0 - FresnelExponential);
			#endif //SPECULAR_HAS_FRESNEL

			half3 InverseTwoSidedLightingMask	= 1 - TwoSidedLightingMask;
//@RockIntNov09 - Joel : I took your changes here
			half3 DiffuseTransferCoefficients	= Phong_DiffuseCoeff( LightMapNormal, GetMaterialDiffusePower(MaterialParameters), TwoSidedLightingMask, InverseTwoSidedLightingMask);
			half3 SpecularTransferCoefficients	= Phong_SpecularCoeff( LightMapReflectionVector, GetMaterialSpecularPower(MaterialParameters), TwoSidedLightingMask, InverseTwoSidedLightingMask);
//@RockIntJan10 - Took Joel's changes, end

		#endif //#if SIMPLE_LIGHTING

		#if SIMPLE_LIGHTING
			#if SIMPLE_TEXTURE_LIGHTMAP
				half3 LightMap = tex2D(LightMapTextures[0],GetLightMapCoordinate(Interpolants)).rgb * LightMapScale[0].rgb;
			#elif SIMPLE_VERTEX_LIGHTMAP
				half3 LightMap = BasePassInterpolants.LightMapA;
			#endif
			Color += pow(LightMap,GetMaterialDiffusePower(MaterialParameters)) * GetMaterialDiffuseColorNormalized(DiffuseColor, MaterialParameters);
		#elif TEXTURE_LIGHTMAP || VERTEX_LIGHTMAP
			#if TEXTURE_LIGHTMAP
				// Average color of the incident lighting over all directions, normalized by the maximum color component.
				half3 NormalizedAverageColor = tex2D(LightMapTextures[0],GetLightMapCoordinate(Interpolants)).rgb;
				//NormalizedAverageColor = pow(NormalizedAverageColor.rgb, 2.2h);
				NormalizedAverageColor.rgb = NormalizedAverageColor.rgb * NormalizedAverageColor.rgb * LightMapScale[0].rgb;
				// Maximum color component of the incident lighting along each of the lightmap basis directions.
				half3 BasisDirectionsMaxComponents = tex2D(LightMapTextures[1],GetLightMapCoordinate(Interpolants)).rgb;
				//BasisDirectionsMaxComponents.rgb = pow(BasisDirectionsMaxComponents.rgb, 2.2h);
				BasisDirectionsMaxComponents.rgb = BasisDirectionsMaxComponents.rgb * BasisDirectionsMaxComponents.rgb * LightMapScale[1].rgb;
			#elif VERTEX_LIGHTMAP
				half3 NormalizedAverageColor = BasePassInterpolants.LightMapA;
				half3 BasisDirectionsMaxComponents = BasePassInterpolants.LightMapB;
			#endif

			#if MATERIAL_LIGHTINGMODEL_CUSTOM
				half3 DiffuseCoefficient = CustomLightingDiffuse;
			#else //MATERIAL_LIGHTINGMODEL_CUSTOM

			// Dot DiffuseTransferCoefficients and BasisDirectionsMaxComponents to scale each max component by the influence of the corresponding basis direction based on the per-pixel normal
			// Compared to directional lightmaps by storing incident color along each basis direction, this encoding has the advantage that it uses 1/3rd less lightmap memory,
			// And the disadvantages that compression artifacts are somewhat worse (compressing three gradient textures and recombining looks better than one gradient texture),
			// And only directional intensities are stored, so varying per-pixel normals can only produce different brightnesses of the lightmap texel color instead of different colors.

				//@Rock - JoelS: Restructured to take our custom passes into account, and introduce a few optimizations...
				half3 LightmapContribution = dot(BasisDirectionsMaxComponents, DiffuseTransferCoefficients);
					#if HAS_LIGHT_WRAPPING 
						#if TEXTURE_LIGHTMAP || SIMPLE_TEXTURE_LIGHTMAP || VERTEX_LIGHTMAP || SIMPLE_VERTEX_LIGHTMAP
							half3 LightWrapping		= GetMaterialLightWrapping(MaterialParameters);
							LightmapContribution	= saturate( LightmapContribution * (1-LightWrapping) + LightWrapping );
						#endif
					#endif				

				// Only apply transmission to diffuse, not specular
				// @Rock - JoelS: inject Epics transmission with fix here:
				LightmapContribution = lerp(LightmapContribution, TwoSidedLightingMask, TwoSidedLightingMask);

				LightmapContribution *= GetMaterialDiffuseColorNormalized(DiffuseColor, MaterialParameters);

				#ifndef DISABLE_LIGHTMAP_SPECULAR
					#if SPECULAR_HAS_FRESNEL
						LightmapContribution = lerp( LightmapContribution, GetMaterialSpecularColor(MaterialParameters) * dot(BasisDirectionsMaxComponents, SpecularTransferCoefficients), Fresnel);
					#else
						LightmapContribution += GetMaterialSpecularColor(MaterialParameters) * dot(BasisDirectionsMaxComponents, SpecularTransferCoefficients);
					#endif //SPECULAR_HAS_FRESNEL
				#endif

				Color += LightmapContribution * NormalizedAverageColor;
			#endif //MATERIAL_LIGHTINGMODEL_CUSTOM

			//@ROCK- Dustin: Rooftop shadowing system
			#if MODULATED_SHADOWMAP
				#if STATICLIGHTING_TEXTUREMASK
					#if STATICLIGHTING_SIGNEDDISTANCEFIELD
						half TransitionDistance = tex2D(ShadowTexture,GetShadowMapCoordinate(Interpolants)).x;
						half ShadowFactor = (TransitionDistance + DistanceFieldParameters.x) * DistanceFieldParameters.y;
						half ShadowMask = pow(saturate(ShadowFactor), DistanceFieldParameters.z); 
					#else
						// static texture shadow map
						half ShadowMask = tex2D(ShadowTexture, GetShadowMapCoordinate(Interpolants)).r;
					#endif
					Color *= lerp(ModShadowColor.rgb, half3(1.h,1.h,1.h), ShadowMask);
				#endif
			#endif
		#endif

		#if ENABLE_SKY_LIGHT
			Color += GetMaterialHemisphereLightTransferFull(
				DiffuseColor,
				CustomLightingDiffuse,
				MaterialParameters,
				normalize(BasePassInterpolants.SkyVector.xyz),
				UpperSkyColor,
				LowerSkyColor) * SkyFactor;
			IncidentLighting += GetMaterialHemisphereLightTransferFull(
				1,
				1,
				MaterialParameters,
				normalize(BasePassInterpolants.SkyVector.xyz),
				UpperSkyColor,
				LowerSkyColor) * SkyFactor;
		#endif

		// Calculate lighting for a SH light
		#if ENABLE_SH_LIGHT
			float3 WorldNormal = TransformTangentVectorToWorld(MaterialParameters.TangentToWorld, MaterialParameters.TangentNormal);
			Color += ComputeSHLighting(DiffuseColor, CustomLightingDiffuse, WorldNormal, MaterialParameters);
			IncidentLighting += ComputeSHLighting(1, 1, WorldNormal, MaterialParameters);
		#endif
		
//@RockIntOct10 - JG: Improved character lighting
		#if ENABLE_A_PLUS_THREE_D_LIGHT
			//#if !MATERIAL_LIGHTINGMODEL_CUSTOM
			//	half3 DiffuseColor = GetMaterialDiffuseColor(MaterialParameters);
			//#else
			//	half3 DiffuseColor = GetMaterialCustomLighting(MaterialParameters);
			//#endif
			Color.rgb+=DiffuseColor*APlus3DLightPixelInfo[APLUS3D_AMBIENT_COLOUR].rgb;
			half3 DummyCombinedShadowFactor=1.0f;
			Color.rgb+=GetMaterialPointLightTransfer(DiffuseColor,SpecularColor,MaterialParameters,0,0,DummyCombinedShadowFactor,false) * APlus3DLightPixelInfo[APLUS3D_COLOUR_0].rgb;
			MaterialParameters.TangentLightVector = normalize((half3)BasePassInterpolants.TangentLightVector1);
			Color.rgb+=GetMaterialPointLightTransfer(DiffuseColor,SpecularColor,MaterialParameters,0,0,DummyCombinedShadowFactor,false) * APlus3DLightPixelInfo[APLUS3D_COLOUR_1].rgb;
			MaterialParameters.TangentLightVector = normalize((half3)BasePassInterpolants.TangentLightVector2);
			Color.rgb+=GetMaterialPointLightTransfer(DiffuseColor,SpecularColor,MaterialParameters,0,0,DummyCombinedShadowFactor,false) * APlus3DLightPixelInfo[APLUS3D_COLOUR_2].rgb;
		#endif

#if !ROCK_STRIP_NORMALS_AND_TANGENTS
		//Flip normals now for lighting because we skipped flipping them in CalculateMaterialParameters
		TwoSidedFlipVector(MaterialParameters);
#endif 
		
		// Calculate lighting for a dynamic light
		#if ENABLE_DIRECTIONAL_LIGHT || ENABLE_MULTITYPE_BASEPASS_LIGHT
			#if STATICLIGHTING_TEXTUREMASK
				#if STATICLIGHTING_SIGNEDDISTANCEFIELD
					half TransitionDistance = tex2D(ShadowTexture,GetShadowMapCoordinate(Interpolants)).x;
					half ShadowFactor = (TransitionDistance + DistanceFieldParameters.x) * DistanceFieldParameters.y;
					half LightMask = pow(saturate(ShadowFactor), DistanceFieldParameters.z); 
				#else
					// static texture shadow map
					half LightMask = tex2D(ShadowTexture, GetShadowMapCoordinate(Interpolants)).r;
				#endif
			#elif STATICLIGHTING_VERTEXMASK
			    // static vertex shadow map
				half LightMask = TangentLightVector.w;
			#else
				half LightMask = 1.0f;
			#endif

			half CombinedShadowFactor = LightMask;
			
			#if DYNAMICALLY_SHADOWED_BASEPASS_LIGHT || TRANSLUCENCY_ONEPASS_DYNAMICALLY_SHADOWED
				if (bReceiveDynamicShadows)
				{
					#if !TRANSLUCENCY_ONEPASS_DYNAMICALLY_SHADOWED && (MATERIALBLENDING_SOLID || MATERIALBLENDING_MASKED || MATERIALBLENDING_SOFTMASKED || TRANSLUCENCY_INHERIT_DOMINANT_SHADOWS_FROM_OPAQUE)
						// .rgb contains accumulated per-object normal shadow factors * light function output
						// .a contains the dominant whole scene shadow, if one was rendered
						half4 AccumulatedShadowFactors = GetLightAttenuation(MaterialParameters.ScreenPosition);
#if ROCK_ENABLE_LIGHTMASS
						// Static branching to only calculate the distance fade when enabled
						if (bEnableDistanceShadowFading)
						{
							half DynamicShadowFraction = DistanceFromCameraFade(MaterialParameters.WorldPosition);
							// Replace the precomputed dominant shadow with the whole scene dynamic shadow based on distance
							CombinedShadowFactor = lerp(CombinedShadowFactor, AccumulatedShadowFactors.a, DynamicShadowFraction);
						}
#endif // ROCK_ENABLE_LIGHTMASS
						// Combine the whole scene dominant light shadow with per-object shadows and the light function if one was rendered
						// Dot the factors with LightChannelMask to select the channel corresponding to the light this object is lit by
						CombinedShadowFactor *= dot(AccumulatedShadowFactors.rgb, LightChannelMask.rgb) + LightChannelMask.w;
					#elif TRANSLUCENCY_RECEIVE_DYNAMIC_SHADOWS_FROM_STATIC
						float DynamicShadowFactor = CalculateForwardDynamicShadowing(MaterialParameters.ScreenPosition);
						CombinedShadowFactor *= DynamicShadowFactor;
					#endif
				}
			#endif

			float SpotLightFalloff = 1.0f;
			#if ENABLE_MULTITYPE_BASEPASS_LIGHT
				// Use static branching to only calculate spotlight falloff for spot lights
				if (bDynamicSpotLight)
				{
					SpotLightFalloff = Square(saturate((dot(normalize((half3)BasePassInterpolants.WorldLightVector.xyz), -SpotDirection) - SpotAngles.x) * SpotAngles.y));
				}
			#endif

			half3 DynamicLightContribution = 
				GetMaterialPointLightTransfer(
					DiffuseColor,
					SpecularColor,
					MaterialParameters,
					#if ENABLE_MULTITYPE_BASEPASS_LIGHT
						BasePassInterpolants.WorldLightVector,
						LightColorAndFalloffExponent.w,
						CombinedShadowFactor,
						!bDynamicDirectionalLight
					#else
						0,
						0,
						CombinedShadowFactor,
						false
					#endif
					)
				* LightColorAndFalloffExponent.rgb
				* SpotLightFalloff;	

			Color += DynamicLightContribution;

			half3 DynamicIncidentLighting = GetMaterialPointLightTransfer(
					1,
					0,
					MaterialParameters,
					#if ENABLE_MULTITYPE_BASEPASS_LIGHT
						BasePassInterpolants.WorldLightVector,
						LightColorAndFalloffExponent.w,
						CombinedShadowFactor,
						!bDynamicDirectionalLight
					#else
						0,
						0,
						CombinedShadowFactor,
						false
					#endif
					)
				* LightColorAndFalloffExponent.rgb
				* SpotLightFalloff;
			IncidentLighting += DynamicIncidentLighting;
		#endif

		#if !MATERIAL_LIGHTINGMODEL_CUSTOM
			#if !SIMPLE_LIGHTING
			Color += DiffuseColor * AmbientColor;
			IncidentLighting += AmbientColor;
			#endif
		#else
			Color += CustomLightingDiffuse * AmbientColor;
			IncidentLighting += AmbientColor;
		#endif

	#endif

	half Opacity = GetMaterialOpacity(MaterialParameters);

	// attenuate blended decals 
	#if MATERIAL_DECAL
		#if MATERIALBLENDING_TRANSLUCENT
			Opacity *= GetMaterialAttenuationDecal(MaterialParameters);
		#elif MATERIALBLENDING_ADDITIVE
			Color *= GetMaterialAttenuationDecal(MaterialParameters);
		#elif MATERIALBLENDING_MODULATE
			Color = lerp(1,Color,GetMaterialAttenuationDecal(MaterialParameters));
		#endif
	#endif

#if NEEDS_BASEPASS_FOGGING
	float4 VertexFog = BasePassInterpolants.VertexFog;
#else
	float4 VertexFog = float4(0,0,0,1);
#endif

	#if MATERIAL_ONELAYERDISTORTION
		// Clamping and scaling to match the normal distortion method
		float2 DistortionOffset = clamp(GetMaterialDistortion(MaterialParameters), -64.0f, 64.0f) * float2( 1.0f / 255.0f, -1.0f / 255.0f);
		// Calculate position to lookup in scene color with the distortion offset
		float2 OffsetSceneTextureCoordinates = MaterialParameters.ScreenPosition.xy / MaterialParameters.ScreenPosition.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz + DistortionOffset;
		// Lookup distorted scene color
		half3 DistortedSceneColor = CalcSceneColor(OffsetSceneTextureCoordinates);
		#if MATERIALBLENDING_TRANSLUCENT
			half3 SourceColor = Color * VertexFog.a + VertexFog.rgb;
			// Manual translucent blending
			OutColor = MaterialGammaCorrect(half4(lerp(DistortedSceneColor, SourceColor, Opacity), 0.0f));
			OutColor = RETURN_COLOR(OutColor);
		#elif MATERIALBLENDING_ADDITIVE
			half3 SourceColor = Color * VertexFog.a * Opacity;
			// Manual additive blending
			OutColor = MaterialGammaCorrect(half4(SourceColor + DistortedSceneColor, 0.0f));
			OutColor = RETURN_COLOR(OutColor);
		#elif MATERIALBLENDING_MODULATE
			// Manual modulative blending
			// RETURN_COLOR not needed with modulative blending
			OutColor = MaterialGammaCorrect(half4(Color * DistortedSceneColor, Opacity));
		#endif
	#else
		#if MATERIALBLENDING_TRANSLUCENT
			OutColor = MaterialGammaCorrect(half4(Color * VertexFog.a + VertexFog.rgb, Opacity));
			OutColor = RETURN_COLOR(OutColor);
		#elif MATERIALBLENDING_ADDITIVE
			OutColor = MaterialGammaCorrect(half4(Color * VertexFog.a * Opacity, 0.0f));
			OutColor = RETURN_COLOR(OutColor);
		#elif MATERIALBLENDING_MODULATE
			// RETURN_COLOR not needed with modulative blending
			OutColor = MaterialGammaCorrect(half4(Color, Opacity));
		#elif MATERIALBLENDING_SOFTMASKED
			OutColor = RETURN_COLOR(MaterialGammaCorrect(float4(Color, Opacity)));
		#else
			#if XBOX
				// Round each channel down to the nearest integer
				half3 QuantizedEmissive = floor(Emissive);
				// Setup the mask to be 1 if any emissive channel was greater than 1, and 0 otherwise
				half EmissiveMask = saturate(dot(QuantizedEmissive, 1));
				half PackedAlpha = (MotionBlurMask + EmissiveMask * 2.0f) / 3.0f;
				// Output the mask bits as scene color alpha (2 bits for scene color alpha on xenon)
				OutColor = RETURN_COLOR(MaterialGammaCorrect(float4(Color,PackedAlpha)));
			#else
				// Output clip space w in scene color alpha
//@Rock - JG: ORTHOGRAPHIC_FRIENDLY_DEPTH
				#if ORTHOGRAPHIC_FRIENDLY_DEPTH
					float W=dot(CameraPlane,float4(MaterialParameters.WorldPosition,1));
				#else
					float W=MaterialParameters.ScreenPosition.w;
				#endif
				OutColor = RETURN_COLOR(MaterialGammaCorrect(float4(Color,EncodeFloatW(W))));
			#endif
		#endif
	#endif

	// NVCHANGE_BEGIN_RS: Adding DX11 Multi-View Soft Shadows
	#if ENABLE_MVSS
		NV_MVSS_COMPUTE_SHADOW(OutColor, BasePassInterpolants.MVSSInterpolants)
	#endif
	// NVCHANGE_END_RS: Adding DX11 Multi-View Soft Shadows

	#if PC_D3D
		#if IMAGE_BASED_REFLECTIONS && SM5_PROFILE
			GetImageReflectionOutputs(MaterialParameters, OutWorldNormal, OutSpecularColorAndPower);
		#endif

		#if MATERIAL_ENABLE_SUBSURFACE_SCATTERING
		float3 SubsurfaceAbsorptionColor = GetMaterialSubsurfaceAbsorptionColor(MaterialParameters);
		float SubsurfaceScatteringRadius = GetMaterialSubsurfaceScatteringRadius(MaterialParameters);
		OutSubsurfaceScatteringAttenuation = float4(SubsurfaceAbsorptionColor,SubsurfaceScatteringRadius);
		OutSubsurfaceInscattering = float4(IncidentLighting * GetMaterialSubsurfaceInscatteringColor(MaterialParameters),0);
		#else
			OutSubsurfaceInscattering = float4(0,0,0,0);
			OutSubsurfaceScatteringAttenuation = float4(0,0,0,0);
		#endif
	#endif

#if MATERIAL_DECAL && XBOX
} //else
#endif

#if ENABLE_TRANSLUCENCY_DOF
	OutTranslucencyDoFBlur = float4(BasePassInterpolants.TranslucencyDoFBlur,0,0,0);
	#if MATERIALBLENDING_TRANSLUCENT
		OutTranslucencyDoFBlur *= Opacity;
	#endif
#endif
}
