/*=============================================================================
	Common.hlsl: Common shader code.
	Copyright 1998-2011 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Definitions.usf"

#if XBOX
	#include "Xbox360/Xbox360Common.usf"
#endif

#if PS3

	// Tangent space bias
	#define TangentBias(x)			( (x / 127.5) - 1 )
	#define TangentNorm(x)			(x / 255.0)
	
	// Register keyword in CG. Note no pixel constant registers on PS3!
	#define VERTEXREGISTER(cx)		: cx
	#define PIXELREGISTER(cx)

	// On PS3, remap Tangent and Binormal to slot 5 and 6, so they don't overlap texcoord 6 and 7
	#define TANGENT					ATTR5
	#define BINORMAL				ATTR6

	// Input semantic for pixel shaders to get the screenspace pixel position (window position)
	#define VPOS					WPOS
	#define VFACE					FACE

	// The PS3 reads our FColor values as ARGB; GBAR swizzles the components into the right order.
	#define FCOLOR_COMPONENT_SWIZZLE .gbar

#elif SM5_PROFILE

	// Tangent space bias
	#define TangentBias(x)			( (x * 2) - 1 )
	#define TangentNorm(x)			(x)

	// Register keyword in HLSL 4.0
	#define VERTEXREGISTER(cx)
	#define PIXELREGISTER(cx)

	// D3D11 vertex declarations read our FColor values as BGRA, so they need to be reversed.
	#define FCOLOR_COMPONENT_SWIZZLE .bgra

#else

	// Tangent space bias
	#define TangentBias(x)			( (x / 127.5) - 1 )
	#define TangentNorm(x)			(x / 255.0)

	// Register keyword in HLSL
	#define VERTEXREGISTER(cx)		: register(cx)
	#define PIXELREGISTER(cx)		: register(cx)

	#define FCOLOR_COMPONENT_SWIZZLE .rgba
#endif

	// TANGENTTOWORLD0 is the first row of the tangent to world matrix, w might be needed for padding and is not used yet.
	// TANGENTTOWORLD2 is the last row of the tangent to world matrix, determinant of tangent basis in w

#if SM5_PROFILE

	// Use the extended SM5 interpolators so that TangentToWorld will work with other features
	#define TANGENTTOWORLD0					TEXCOORD10
	#define TANGENTTOWORLD2					TEXCOORD11

	// _centroid is needed to get better quality with MSAA

	// The D3D shader compiler combines _centroid and non controid. Using float3 would results in a internal
	// shader compiler error. This block is using float4 to prevent that.
	#define TANGENTTOWORLD_INTERPOLATOR_BLOCK	float4 TangentToWorld0 : TEXCOORD10_centroid; float4	TangentToWorld2	: TEXCOORD11_centroid;

#else

	// Note that on PS3 COLOR0 and COLOR1 are fixed point and clamped to [0,1], but higher precision than 8 bit.
	// We use PackColorN() and UnpackColorN() helper functions to pass vectors through a COLOR interpolator.
	#define TANGENTTOWORLD0					COLOR0
	#define TANGENTTOWORLD2					COLOR1

	#define TANGENTTOWORLD_INTERPOLATOR_BLOCK	float3 TangentToWorld0 : TANGENTTOWORLD0; float4	TangentToWorld2	: TANGENTTOWORLD2;
#endif

#if PS3 || OPENGL
	// Potentially normalizes and remaps a vector to [0,1] range, to fit in a COLOR interpolator.
	float3	PackColor3( float3 UnpackedVector )
	{
		return normalize(UnpackedVector)*0.5f + 0.5f;
	}
	// Potentially normalizes and remaps a vector to [0,1] range, to fit in a COLOR interpolator.
	float4	PackColor4( float4 UnpackedVector )
	{
		float4 PackedVector;
		PackedVector.xyz = normalize(UnpackedVector.xyz);
		PackedVector.w = UnpackedVector.w;
		return PackedVector*0.5f + 0.5f;
	}
	// Potentially remaps a vector from [0,1] to [-1,+1] range, to unpack a vector from a COLOR interpolator.
	half3	UnpackColor3( half3 PackedVector )
	{
		return PackedVector*2.0f - 1.0f;
	}
	// Potentially remaps a vector from [0,1] to [-1,+1] range, to unpack a vector from a COLOR interpolator.
	half4	UnpackColor4( half4 PackedVector )
	{
		return PackedVector*2.0f - 1.0f;
	}
#else
	// Potentially normalizes and remaps a vector to [0,1] range, to fit in a COLOR interpolator.
	float3	PackColor3( float3 UnpackedVector )
	{
		return UnpackedVector;
	}
	// Potentially normalizes and remaps a vector to [0,1] range, to fit in a COLOR interpolator.
	float4	PackColor4( float4 UnpackedVector )
	{
		return UnpackedVector;
	}
	// Potentially remaps a vector from [0,1] to [-1,+1] range, to unpack a vector from a COLOR interpolator.
	half3	UnpackColor3( half3 PackedVector )
	{
		return PackedVector;
	}
	// Potentially remaps a vector from [0,1] to [-1,+1] range, to unpack a vector from a COLOR interpolator.
	half4	UnpackColor4( half4 PackedVector )
	{
		return PackedVector;
	}
#endif

float UnClampedPow(float X, float Y)
{
	return pow(X, Y);
}
float2 UnClampedPow(float2 X, float2 Y)
{
	return pow(X, Y);
}
float3 UnClampedPow(float3 X, float3 Y)
{
	return pow(X, Y);
}
float4 UnClampedPow(float4 X, float4 Y)
{
	return pow(X, Y);
}

// Clamp the base, so it's never <= 0.0f (INF/NaN).
float ClampedPow(float X,float Y)
{
	// Workaround for a bug in the March 2009 DX SDK that compiles a scalar pow(max(abs(X), 0.0001f), Y) as:
	// max( pow( abs(X), 80 ), pow( 0.0001f, 80 ) ); 
	// The pow( 0.0001f, 80 ) generates a denorm. 
	#if PC_D3D
		return abs(X) < 0.000001f ? 0 : pow(abs(X), Y);
	#else
		return pow(max(abs(X),0.000001f),Y);
	#endif
}
float2 ClampedPow(float2 X,float2 Y)
{
	return pow(max(abs(X),float2(0.000001f,0.000001f)),Y);
}
float3 ClampedPow(float3 X,float3 Y)
{
	return pow(max(abs(X),float3(0.000001f,0.000001f,0.000001f)),Y);
}
float4 ClampedPow(float4 X,float4 Y)
{
	return pow(max(abs(X),float4(0.000001f,0.000001f,0.000001f,0.000001f)),Y);
}

/** 
 * Use this function to compute the pow() in the specular computation.
 * This allows to change the implementation depending on platform or it easily can be replaced by some approxmation.
 * It only provides the precision needed (half).
 */
half PhongShadingPow(half X, half Y)
{
	// The following clamping is done to prevent NaN being the result of the specular power computation.
	// Clamping has a minor performance cost.

	// In HLSL pow(a, b) is implemented as exp2(log2(a) * b).

	// For a=0 this becomes exp2(-inf * 0) = exp2(NaN) = NaN.

	// As seen in #TTP 160394 "QA Regression: PS3: Some maps have black pixelated artifacting."
	// this can cause severe image artifacts (problem was caused by specular power of 0, lightshafts propagated this to other pixels).
	// The problem appeared on PlayStation 3 but can also happen on similar PC NVidia hardware.

	// In order to avoid platform differences and rarely occuring image atrifacts we clamp the base.

	// Note: Clamping the exponent seemed to fix the issue mentioned TTP but we decided to fix the root and accept the
	// minor performance cost.

	return ClampedPow(X, Y);
}

#if PS3
	// When multiplying with a matrix that is passed in externally through a matrix parameter, you MUST use MulMatrix.
	// When multiplying by a generated matrix (float3x3(VecA, VecB, VecC)), you MUST use mul
	// Note that MulMatrix also works for multiplying vector by matrix (transforming by transposed matrix), e.g. MulMatrix( Vect, Mtx ).
	#define MulMatrix(Mtx, Vect)	mul(Vect, Mtx)
	#define MulBone(Mtx, Vect)		mul(Mtx, Vect)
	
	// Clamp the base, so it's never <= 0.0f on PS3 (INF/NaN).
//	#define pow(x,y)				pow( max(abs(x), 0.000001f), (y) )
#else
	#define MulMatrix(Mtx, Vect)	mul(Mtx, Vect)
	#define MulBone(Mtx, Vect)		mul(Vect, Mtx)

	// It's necessary to use these whenever you're reading a depth value from a depth texture
    #define texDepth2D				tex2D
	#define texDepth2Dlod			tex2Dlod
	#define texDepth2Dproj			tex2Dproj
#endif

#if !SM5_PROFILE
	// SM5 is the only platform that natively supports uints in shaders; we just use floats on other platforms.
	#define uint4	float4

	// SM5 is the only platform that needs tex2Dbias currently, but the material compiler emits tex2Dbias for all platforms.
	// On Xbox 360, tex2Dbias is considerably slower than tex2D so we override it.
	#define tex2Dbias tex2D
#endif

#if !VERTEXSHADER
	#undef VERTEXREGISTER
	#define VERTEXREGISTER(cx)
#endif

#if !PIXELSHADER
	#undef PIXELREGISTER
	#define PIXELREGISTER(cx)
#endif

// Pixel and vertex shader constant registers that are reserved by the Engine.
// ----------------------------------------------------------------------------------------
#if OPENGL
#define PSR_ColorBiasFactor         c217  // Factor applied to the color output from the pixelshader
#define PSR_ScreenPositionScaleBias c218  // Converts projection-space XY coordinates to texture-space UV coordinates
#define PSR_MinZ_MaxZ_Ratio         c219  // Converts device Z values to clip-space W values
#define PSR_NvStereoEnabled         c220  // Whether stereo is enabled on the current rendering device
#define PSR_DiffuseOverride         c221  // Overrides GetMaterialDiffuseColor for visualization
#define PSR_SpecularOverride        c222  // Overrides GetMaterialSpecularColor for visualization
#define PSR_ViewOrigin              c223  // World space position of the camera

#define VSR_ViewProjMatrix          c249  // View-projection matrix, transforming from World space to Projection space
#define VSR_ViewOrigin              c253  // World space position of the camera
#define VSR_PreViewTranslation      c254  // Offset applied to LocalToWorld to reduce precision problems far from the world space origin
#define VSR_TemporalAAParameters    c255
#else
// These #defines must match the enums EPixelShaderRegisters and EVertexShaderRegister
// as they are defined in RHI.h.
#define PSR_ColorBiasFactor         c0  // Factor applied to the color output from the pixelshader
#define PSR_ScreenPositionScaleBias c1  // Converts projection-space XY coordinates to texture-space UV coordinates
#define PSR_MinZ_MaxZ_Ratio         c2  // Converts device Z values to clip-space W values
#define PSR_NvStereoEnabled         c3  // Whether stereo is enabled on the current rendering device
#define PSR_DiffuseOverride         c4  // Overrides GetMaterialDiffuseColor for visualization
#define PSR_SpecularOverride        c5  // Overrides GetMaterialSpecularColor for visualization
#define PSR_CameraPlane				c6	//@Rock - JG : Fix for depth biased blends in lods. 
#define PSR_ViewOrigin              PSR_CameraPlane

#define VSR_ViewProjMatrix          c0  // View-projection matrix, transforming from World space to Projection space
#define VSR_ViewOrigin              c4  // World space position of the camera
#define VSR_PreViewTranslation      c5  // Offset applied to LocalToWorld to reduce precision problems far from the world space origin
#if SM5_PROFILE
#define VSR_TemporalAAParameters    c6
#endif
#endif

// Helper macro used to interpolate the given member
#define TESSELLATION_INTERPOLATE_MEMBER(member) O.member = a.member * aInterp + b.member * bInterp

#if SM5_PROFILE

	// Warning: The register offsets MUST match what is defined in D3D11ConstantBuffer.h!
	cbuffer VSOffsetConstants : register(b1)
	{
		/** Note - the vertex shader ViewProjectionMatrix is actually TranslatedViewProjectionMatrix, since camera position has been removed from it. */
		float4x4	ViewProjectionMatrix	VERTEXREGISTER(VSR_ViewProjMatrix);
		/** Note - the vertex shader CameraPosition has been translated so the camera position is at the origin. */
		float4		CameraPositionVS		VERTEXREGISTER(VSR_ViewOrigin);
		float4		PreViewTranslation		VERTEXREGISTER(VSR_PreViewTranslation);
		float4		TemporalAAParameters	VERTEXREGISTER(VSR_TemporalAAParameters);
	};
	cbuffer PSOffsetConstants : register(b2)
	{
		// Converts projection-space XY coordinates to texture-space UV coordinates
		float4		ScreenPositionScaleBias		PIXELREGISTER(PSR_ScreenPositionScaleBias);
		float4	    MinZ_MaxZRatio				PIXELREGISTER(PSR_MinZ_MaxZ_Ratio);
		float4		DiffuseOverrideParameter	PIXELREGISTER(PSR_DiffuseOverride);
		float4		SpecularOverrideParameter	PIXELREGISTER(PSR_SpecularOverride);
		float		NvStereoEnabled				PIXELREGISTER(PSR_NvStereoEnabled);
	};
	#if SM5_PROFILE
		// Next is b4 as b3 is used in skinning VF (optionally)
		cbuffer HSOffsetConstants : register(b4)	
		{
			// Used to control level of tesselation
			float		GlobalTesselationFactor;
		};
		cbuffer DSOffsetConstants : register(b5)	
		{
			/** Note - the domain shader ViewProjectionMatrix is actually TranslatedViewProjectionMatrix, since camera position has been removed from it. */
			float4x4	ViewProjectionMatrixDS;
			/** Note - the domain shader CameraPosition has been translated so the camera position is at the origin. */
			float4		CameraPositionDS;
			float4		TemporalAAParametersDS;
		};

		/** Parameters bound and set by FDeferredVertexShaderParameters */
		// Transform from [-1, 1] screen space to world.
		// If this is used in a vertex shader, it will have the PreViewTranslation built in, otherwise not.
		float4x4 ScreenToWorldMatrix;

	#endif
#else
	/** Note - the vertex shader ViewProjectionMatrix is actually TranslatedViewProjectionMatrix, since camera position has been removed from it. */
	float4x4	ViewProjectionMatrix		VERTEXREGISTER(VSR_ViewProjMatrix);
	/** Note - the vertex shader CameraPosition has been translated so the camera position is at the origin. */
	float4		CameraPositionVS			VERTEXREGISTER(VSR_ViewOrigin);
	float4		PreViewTranslation			VERTEXREGISTER(VSR_PreViewTranslation);
	static const float4 TemporalAAParameters = float4(0,0,0,0);

	// Converts projection-space XY coordinates to texture-space UV coordinates
	float4		ScreenPositionScaleBias		PIXELREGISTER(PSR_ScreenPositionScaleBias);
	float4	    MinZ_MaxZRatio				PIXELREGISTER(PSR_MinZ_MaxZ_Ratio);
#if SM3_PROFILE
	float		NvStereoEnabled				PIXELREGISTER(PSR_NvStereoEnabled);
	float4		DiffuseOverrideParameter	PIXELREGISTER(PSR_DiffuseOverride);
	float4		SpecularOverrideParameter	PIXELREGISTER(PSR_SpecularOverride);
	float4		CameraPlane					PIXELREGISTER(PSR_CameraPlane);
#endif
#endif

#if !PC_D3D
	// Define these to constants on non-PC platforms so they are optimized out
	static const float4 DiffuseOverrideParameter = float4(0,0,0,1);
	static const float4 SpecularOverrideParameter = float4(0,0,0,1);
#endif

#if XBOX
	// The x component is set to 1 when rendering to an LDR buffer, otherwise 2^SCENE_COLOR_BIAS_FACTOR_EXP (See XeD3DRenderTarget.cpp)
	float4	SCENE_COLOR_BIAS_FACTOR			PIXELREGISTER(PSR_ColorBiasFactor);
#else
	#define SCENE_COLOR_BIAS_FACTOR			1.0f
#endif

/** 
 * Whether to output shadow depths as Z/W (z buffer) or to output just W (linear).
 * Note: This must match the value of ShouldRenderNonLinearShadowDepths() in ShadowRendering.h!
 */
#define NON_LINEAR_SHADOW_DEPTHS SM5_PROFILE

// Mirrors the value used in FPerspectiveMatrix for creating a perspective matrix with an infinite far plane
#define Z_PRECISION	0.001f

#if MATERIAL_TWOSIDED
	// For two sided surfaces, this is the sign that should be applied to the normal.
	// Two sided surfaces are only drawn once without backface culling, and VFACE
	// is used to determine which side is being drawn.  TwoSidedSign contains useful information
	// about whether the model is flipped.
	half TwoSidedSign;
#endif

sampler2D 	SceneDepthTexture;
sampler2D	SceneColorTexture;

#if ALLOW_NVIDIA_STEREO_3D
sampler2D NvStereoFixTexture;
#endif

// Because the pixel shader is transforming the eye position to clip itself, it's transforming to mono-space clip space.
// However, if the game is running in stereo, the position of objects will have been shifted to stereo-clip space. This
// code looks up values for each eye to correct for the amount of separation that has occurred, or it returns the original
// position if stereo is disabled.
float4 MonoToStereoClipPos(float4 monoClipPos)
{
#if ALLOW_NVIDIA_STEREO_3D
	if (NvStereoEnabled)
	{
		// Correct would be float2(0.0625f, 0.5f) but it should not be changed without proper testing.
		float2 stereoParms = tex2D(NvStereoFixTexture, float2(0.0625f, 0.0f)).rg;

		float4 stereoClipPos = monoClipPos;

		// Duplicate the stereo transform here.
		// NVCHANGE_BEGIN: Calvin Lin -- 3D Vision Fixes
		if (stereoClipPos.w != 1.0f)
		// NVCHANGE_END: Calvin Lin -- 3D Vision Fixes
		stereoClipPos.x += stereoParms.x * (stereoClipPos.w - stereoParms.y);
		return stereoClipPos;
	}
#endif
    // No correction needed for consoles, or old hardware
    return monoClipPos;
}

// NVCHANGE_BEGIN: Calvin Lin -- 3D Vision Fixes
float4 StereoToMonoClipPos(float4 stereoClipPos)
{
#if ALLOW_NVIDIA_STEREO_3D
	if (NvStereoEnabled)
	{
		float2 stereoParms = tex2D(NvStereoFixTexture, float2(0.0625f, 0)).xy;

		float4 monoClipPos = stereoClipPos;

		// De-stereo here.
		if (monoClipPos.w != 1.0f)
			monoClipPos.x -= stereoParms.x * (monoClipPos.w - stereoParms.y);

		return monoClipPos;
	}
#endif
    // No correction needed for consoles, or old hardware
    return stereoClipPos;
}
// NVCHANGE_END: Calvin Lin -- 3D Vision Fixes


// ----------------------------------------------------------------------------------------

#if XBOX
	float4 BiasColor( float4 Color )
	{
		return float4( Color.rgb * SCENE_COLOR_BIAS_FACTOR.x, Color.a );
	}
	// RETURN_COLOR should only be used when rendering to the SceneColor surface
	#define RETURN_COLOR( Color ) BiasColor( Color );
#else
	// We don't use an inline function so we can avoid type promotion/ coercion.
	#define RETURN_COLOR( Color ) ( Color )
#endif

//the largest value any color component is allowed to have, scene color is clamped to this in DOFAndBloomGatherPixelShader.usf
//also used to pack color into the fixed point filter buffer, which requires a range of [0-1]
#define MAX_SCENE_COLOR 4.0f

float Square(float A)
{
	return A * A;
}
float2 Square(float2 A)
{
	return A * A;
}
float3 Square(float3 A)
{
	return A * A;
}
float4 Square(float4 A)
{
	return A * A;
}


float4 ExpandRGBE( float4 RGBE )
{
	return float4( ldexp( RGBE.xyz, 255.0 * RGBE.w - 128.0 ), 1.0 );
}

float4 ExpandCompressedRGBE( float4 RGBE )
{
	return float4( ldexp( RGBE.xyz, 255.0 / 16.0 * RGBE.w - 8.0 ), 1.0 );
}

//------------------------------------------------------------------------------------------------------------------------------------------------------
//	Lighting equations:
//------------------------------------------------------------------------------------------------------------------------------------------------------
//@Rock - JoelS: Restructuring lighting equations and moving them here. This is to optomise and reduce code duplication between BasePassPixelShader.usf
// and *LightPixelShader.usf, and also within the lighting models themselves.

//============================
// Static lighting functions:
//============================

half3 Phong_DiffuseCoeff(half3 LightMapNormal, half DiffusePower, half3 TwoSidedLightingMask, half3 InverseTwoSidedLightingMask)
{
	//Square saturated LightMapNormal (saving 1 instruction)
	half3 result	= saturate(LightMapNormal);
	result			*= result;

	//Check if there's a node attached to DiffusePower.
	//We now check this instead of relying on the compiler since it saves us up to 2 instructions when nothing's connected.
#if HAS_DIFFUSE_POWER
	result			= pow( result, DiffusePower	);
#endif //HAS_DIFFUSE_POWER

	//Fix for transmission ported to the basepasspixelshader.usf and removed here:
	//result			= result * InverseTwoSidedLightingMask + TwoSidedLightingMask;

	return result;
}

half3 Phong_SpecularCoeff(half3 LightMapReflectionVector, half SpecularPower, half3 TwoSidedLightingMask, half3 InverseTwoSidedLightingMask)
{
	half3 result = pow(	saturate(LightMapReflectionVector),	SpecularPower ); //removed * InverseTwoSidedLightingMask; //removed (SpecularPower + 1)
						//Approx. energy conservation
						#if SPECULAR_CONSERVE_ENERGY
							#if SPECULAR_BLINNPHONG
								result *= ((SpecularPower+8.h)/8.h);
							#else //SPECULAR_BLINNPHONG
								result *= ((SpecularPower+2.h)/8.h);		//using microfacet theory alternative for Phong
							#endif //SPECULAR_BLINNPHONG
						#endif //defined(SPECULAR_CONSERVE_ENERGY)
	return result;
}

//=============================
// Dynamic lighting functions:
//=============================
//Get Lambert:
//-------------
//x = [-1...1] range
//y = saturated 0...1 range
//z = spec mask if required
half3 getLambert(half3 N,half3 L)
{
	half3 lambert = dot(N,L);
	lambert.y = saturate(lambert.x);

		#if SPECULAR_MASK_BY_SHADING
			lambert.z	= saturate(lambert.y * 4);	//multiply by the pre-saturated value .y to save an instruction here.
		#endif //SPECULAR_MASK_BY_SHADING

	return lambert;
}

//Diffuse lighting:
//-----------------
//Return the base diffuse lighting response, including .rgb components.
half3 computeDiffuseLighting( in half3 lambert, in half3 LightWrapping, in half3 DiffusePower )
{
#if HAS_LIGHT_WRAPPING
	half3 result		= saturate( lambert.x * (1-LightWrapping) + LightWrapping );
#else //HAS_LIGHT_WRAPPING
	half3 result		= lambert.y;
#endif //HAS_LIGHT_WRAPPING


//Check if there's a node attached to DiffusePower. 
//We now check this instead of relying on the compiler since it can save us 2 instructions when nothing's connected.
#if HAS_DIFFUSE_POWER
	result.rgb			= pow( result, DiffusePower);
#endif //HAS_DIFFUSE_POWER

return result.rgb;
}

//Specular reflection:
//--------------------
//Computes the phong or blinn-phong specular reflection
half3 computeSpecular( in half3 result, in half3 R, in half3 E, in half3 L, in half3 N, in half3 lambert, in half SpecularPower, in half3 SpecularColor, in half SpecularPower2, in half3 SpecularColor2, in half FresnelMin, in half FresnelPower)
{
	//Specular reflection:
#ifndef DISABLE_DYNAMIC_SPECULAR
	#if SPECULAR_BLINNPHONG
		half3 ReflectionVector	= normalize(E + L); //Half Vector
		half SpecularIncidence	= saturate(dot(ReflectionVector,N));
	#else //SPECULAR_BLINNPHONG
		half3 ReflectionVector	= R;
		half SpecularIncidence	= saturate(dot(ReflectionVector,L));
	#endif //SPECULAR_BLINNPHONG

	#if HAS_SPECULAR2
		half2 dualSpec			= pow( SpecularIncidence, half2(SpecularPower, SpecularPower2) );
		half3 SpecularResult	= (dualSpec.x * SpecularColor.rgb + dualSpec.y * SpecularColor2.rgb)
	#else //HAS_SPECULAR2
		half3 SpecularResult	= ( pow( SpecularIncidence, SpecularPower ) * SpecularColor.rgb )
	#endif //HAS_SPECULAR2

						//Approx. energy conservation 
						#if SPECULAR_CONSERVE_ENERGY
							#if SPECULAR_BLINNPHONG
								* ((SpecularPower+8)/8)
							#else //SPECULAR_BLINNPHONG
								* ((SpecularPower+2)/8)		//using microfacet theory alternative for Phong
							#endif //SPECULAR_BLINNPHONG
						#endif //defined(SPECULAR_CONSERVE_ENERGY)

						//Mask specular by the self-shading area. Nicer than masking by the crude shadow mask
						#if SPECULAR_MASK_BY_SHADING
							* lambert.z
						#endif //SPECULAR_MASK_BY_SHADING
							;

	#if SPECULAR_HAS_FRESNEL
		#if SPECULAR_BLINNPHONG
			half FresnelIncidence	= saturate(dot(ReflectionVector,E));
		#else //SPECULAR_BLINNPHONG
			half FresnelIncidence	= saturate(dot(L,E) * 0.5 + 0.5);
		#endif //SPECULAR_BLINNPHONG

		half FresnelExponential = pow(1.0 - saturate(FresnelIncidence), FresnelPower);
		// interpolate between FresnelMin and 1.0 by exponential term
		half Fresnel = FresnelExponential + FresnelMin * (1.0 - FresnelExponential);
		result					= lerp( result, SpecularResult, Fresnel);

	#else //SPECULAR_HAS_FRESNEL
		result					+= SpecularResult;
	#endif //SPECULAR_HAS_FRESNEL

#endif //DISABLE_DYNAMIC_SPECULAR

		return result;
}

//Anisotropic specular reflection:
//---------------------------------
//Computes the phong or blinn-phong anisotropic specular reflection
half3 computeSpecularAnisotropic( in half3 result, in half3 R, in half3 T, in half3 E, in half3 L, in half3 N, in half3 lambert, in half SpecularPower, in half3 SpecularColor, in half SpecularPower2, in half3 SpecularColor2, in half FresnelMin, in half FresnelPower)
{
#ifndef DISABLE_DYNAMIC_SPECULAR
// always use blinn-phong half-vector...
	half3 ReflectionVector	= 0.5 * ( E + L ); //normalize(E + L); //Half Vector

	half anisotropy	= Square(dot( T, ReflectionVector ));
	anisotropy		= max( 1.0 - anisotropy, 0.01);

	#if HAS_SPECULAR2
		half2 dualSpec			= pow( anisotropy, half2(SpecularPower,SpecularPower2) * 25.f );
		half3 SpecularResult	= (dualSpec.x * SpecularColor.rgb + dualSpec.y * SpecularColor2.rgb)
	#else //HAS_SPECULAR2
		half3 SpecularResult	= ( pow( anisotropy, SpecularPower * 25.f ) * SpecularColor.rgb )
	#endif //HAS_SPECULAR2

	//Approx. energy conservation 
	#if SPECULAR_CONSERVE_ENERGY
			* ((SpecularPower+400)/800)
	#endif //defined(SPECULAR_CONSERVE_ENERGY)

	//Mask specular by the self-shading area. Nicer than masking by the crude shadow mask
	#if SPECULAR_MASK_BY_SHADING
		* lambert.z
#else
		* lambert.y		//<- specular masking is always enabled for anisotropic shading. Revert to .y to save 1 ALU
	#endif //SPECULAR_MASK_BY_SHADING
	;


	#if SPECULAR_HAS_FRESNEL
		half FresnelIncidence	= saturate(dot(ReflectionVector,E));
		half FresnelExponential = pow(1.0 - saturate(FresnelIncidence), FresnelPower);
		// interpolate between FresnelMin and 1.0 by exponential term
		half Fresnel			= FresnelExponential + FresnelMin * (1.0 - FresnelExponential);
		result					= lerp( result, SpecularResult, Fresnel);

	#else //SPECULAR_HAS_FRESNEL
		result					+= SpecularResult;
	#endif //SPECULAR_HAS_FRESNEL

#endif //DISABLE_DYNAMIC_SPECULAR

		return result;
}

// Subsurface Scattering:
//-----------------------
//Many vulgar simplifications of http://http.developer.nvidia.com/GPUGems3/gpugems3_ch14.html
//cheapest in 5 instructions

//There are two main mutually exclusive paths for this effect:
// - Enable the effect if either the SSSNormal or SSSMask is active.
// - We can fallback to the vertex normals if no SSSNormal exists
// - We can fallback to the human measurement data if no SSSMask is used

half3 TransColFull(half s) 
{
  return float3(0.233, 0.455, 0.649) * exp(-s*s/0.0064) +
         float3(0.1,   0.336, 0.344) * exp(-s*s/0.0484) +
         float3(0.118, 0.198, 0.0)   * exp(-s*s/0.187)  +
         float3(0.113, 0.007, 0.007) * exp(-s*s/0.567)  +
         float3(0.358, 0.004, 0.0)   * exp(-s*s/1.99)   +
         float3(0.078, 0.0,   0.0)   * exp(-s*s/7.41);
}

half3 TransCol(half s, half3 ColCoeff) 
{
  half3 absorptionCoeff = exp2(-s / (0.0001h + ColCoeff) ); //half3(2.0625h, 0.3625h, 0.0875h)
  return absorptionCoeff;
}

half3 computeSSS(	in half3 result, 
					in half3 lambert, 
					in half3 SSSMask, 
					in half SSSRadius, 
					in half3 SSSNormal, 
					in half3 L, 
					in half3 N, 
					in half3 E, 
					in half3 R, 
					in half3 TransmissionMask, 
					in half3 DiffuseColor, 
					in half3 SSSColourDiffuse, 
					in half3 SSSColourEpidermal, 
					in half3 SSSColourSubdermal, 
					in half3 SSSColourTransmittance )
{
#if HAS_SSS_NORMAL || HAS_SSS_MASK

	//Combined weighted sum of the diffusion profile which emulates dipole diffusion. This in turn emulates the gaussian distributed min/max kernel
	//weights, and breaks it into summed weighted averages for that min/max (hard/soft) profile.
	#if HAS_SSS_MASK
		half3 RadianceProfileSoft = SSSMask;
	#else
		//Human skin measurement defaults:
		half3 RadianceProfileSoft = 1; //half3(2.0625h, 0.3625h, 0.0875h); //half3(0.9988h, 0.3076h, 0.146h);
	#endif //HAS_SSS_MASK

	#if HAS_SSS_NORMAL
		half soft = dot(L.xyz, SSSNormal.xyz);
#else
		//Fallback and use the equivelent of lit vertex normals (pos light.z vector in tangent space)
		half soft = lerp(L.z, lambert.x, 0.25h); //L.z;
	#endif //HAS_SSS_NORMAL

//@Rock - JoelS: our old sss term...
	//result		= RadianceProfileSoft * soft + (1-RadianceProfileSoft) * result;

//@Rock - JoelS: our shiney NEW sss term...
	//result		+= soft * (1 - result) * RadianceProfileSoft;

//@Rock - JoelS: our experimental sss term...
	//deep and shallow...
	//result		+= ( (saturate(dot(L, SSSNormal) * float3(1,1,0) ) * RadianceProfileSoft)
	//			+ ( soft * float3(0.25,0.4,0.27) )  )
	//			* (1 - result);

//@Rock - JoelS: Our crazy cheap sss term (which still looks good)...
	//result		+= max(0,(soft+RadianceProfileSoft) * (1 - result)) * RadianceProfileSoft;
	//result		+= max(0,(soft) * (1 - result));// * RadianceProfileSoft;

//@Rock - JoelS: RGB normal profile:
	//half3 SSSResult;
	//SSSResult.r		= saturate(dot(L.xyz, lerp(N.xyz, SSSNormal.xyz, RadianceProfileSoft.r) ));
	//SSSResult.g		= saturate(dot(L.xyz, lerp(N.xyz, SSSNormal.xyz, RadianceProfileSoft.g) ));
	//SSSResult.b		= saturate(dot(L.xyz, lerp(N.xyz, SSSNormal.xyz, RadianceProfileSoft.b) ));
	//result.rgb		= SSSResult; //max( result.rgb,SSSResult.rgb);

//@Rock - JoelS: Absorbtion coefficient
	//half DepthApprox	= 1-lambert.x;
	//half MaxRadii		= saturate(0.1 + soft);
	//half3 SSSResult		= TransCol(DepthApprox, RadianceProfileSoft) * MaxRadii;
	//result				*= 1 - SSSResult;
	//result				+= SSSResult;

//@Rock - JoelS: Multi layer
	half3 MaxRadii		= SSSRadius * half3(-0.1h, 0.1h, 0.3h);

	half3 diffuse		= result * SSSColourDiffuse;																//* half3(0.75h, 0.9h , 1.0h) * 0.3h;
	half3 epidermal		= saturate( MaxRadii.x + lambert.x) * SSSColourEpidermal;													//* half3(1.h, 0.85h , 0.6h) * 0.5h );
	half3 subdermal		= saturate( MaxRadii.y + soft ) * SSSColourSubdermal;										//* half3(0.95h, 0.5h, 0.2h) * 0.4h );
	half3 transmittance	= saturate((MaxRadii.z + L.z ) * saturate(dot(-E + L,-N) ) ) * SSSColourTransmittance;		//* half3(0.7h, 0.1h, 0.1h) * 0.5h );

	result				*= saturate(1.0h - RadianceProfileSoft);
	result				+= (diffuse + epidermal + subdermal + transmittance) * RadianceProfileSoft;					//lerp(result, diffuse + epidermal + subdermal + transmittance, RadianceProfileSoft);


#endif //HAS_SSS_NORMAL || HAS_SSS_MASK

	// Only apply transmission to diffuse, not specular
	// @Rock - JoelS: inject Epics transmission with fix here:
	result = lerp(result, TransmissionMask, TransmissionMask);

	return result;
}



half3 PointLightPhong(	  half3 DiffuseColor
						, half DiffusePower
						, half3 TransmissionMask
						, half3 SpecularColor
						, half SpecularPower
						, half FresnelMin
						, half FresnelPower
						, half3 LightWrapping
						, half3 SSSNormal
						, half3 SSSMask
						, half SSSRadius
						, half3 SpecularColor2
						, half SpecularPower2
						, half3 SSSColourDiffuse
						, half3 SSSColourEpidermal
						, half3 SSSColourSubdermal
						, half3 SSSColourTransmittance
						, half3 L
						, half3 E
						, half3 N
						, half3 R)
{
	half3 lambert			= getLambert(N,L);
	half3 result;
	result.rgb				= computeDiffuseLighting( lambert, LightWrapping, DiffusePower );
	result.rgb				= computeSSS(	result, 
											lambert, 
											SSSMask, 
											SSSRadius, 
											SSSNormal, 
											L, 
											N, 
											E, 
											R, 
											TransmissionMask, 
											DiffuseColor, 
											SSSColourDiffuse, 
											SSSColourEpidermal, 
											SSSColourSubdermal, 
											SSSColourTransmittance);
	result.rgb				*= DiffuseColor;

	result.rgb				= computeSpecular( result, R, E, L, N, lambert, SpecularPower, SpecularColor, SpecularPower2, SpecularColor2, FresnelMin, FresnelPower);

	return result;
}



float3 PointLightAnisotropic(	half3 DiffuseColor
								, half DiffusePower
								, half3 TransmissionMask
								, half3 SpecularColor
								, half SpecularPower
								, half FresnelMin
								, half FresnelPower
								, half3 LightWrapping
								, half3 SSSNormal
								, half3 SSSMask
								, half SSSRadius
								, half3 SpecularColor2
								, half SpecularPower2
								, half3 SSSColourDiffuse
								, half3 SSSColourEpidermal
								, half3 SSSColourSubdermal
								, half3 SSSColourTransmittance
								, half3 L
								, half3 E
								, half3 N
								, half3 R
								, half3 T)
{
	half3 lambert			= getLambert(N,L);
	half3 result;
	result.rgb				= computeDiffuseLighting( lambert, LightWrapping, DiffusePower );
	result.rgb				= computeSSS(	result, 
											lambert, 
											SSSMask, 
											SSSRadius, 
											SSSNormal, 
											L, 
											N, 
											E, 
											R, 
											TransmissionMask, 
											DiffuseColor, 
											SSSColourDiffuse, 
											SSSColourEpidermal, 
											SSSColourSubdermal, 
											SSSColourTransmittance);
	result.rgb				*= DiffuseColor;

//@Rock - JoelS: Rolling our own custom anisotropic lighting response.
// Has cut our test case materials down from 72 instructions to 60.
	result.rgb				= computeSpecularAnisotropic( result, R, T, E, L, N, lambert, SpecularPower, SpecularColor, SpecularPower2, SpecularColor2, FresnelMin, FresnelPower);

	return result;
}

float4 PreviousLighting(float4 ScreenPosition)
{
	return tex2D(SceneColorTexture,ScreenPosition.xy / ScreenPosition.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz);
}

float RadialAttenuation(float3 WorldLightVector,half FalloffExponent)
{
	return pow(
		1.0f - saturate(dot(WorldLightVector,WorldLightVector)),
		FalloffExponent
		);
}

sampler2D	LightAttenuationTexture;

/** Fetches the values in the light attenuation buffer. */
half4 GetLightAttenuation(float4 ScreenPosition)
{
	float2 ClipPos = float2(ScreenPosition.xy / ScreenPosition.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz);
	float4 Attenuation = tex2D(LightAttenuationTexture, ClipPos);
	// Undo the sqrt that was used to encode
	return Square(Attenuation);
}

/** Converts a linear input value into a value to be stored in the light attenuation buffer. */
float EncodeLightAttenuation(float InColor)
{
	// Apply a 1/2 power to the input, which allocates more bits for the darks and prevents banding
	// Similar to storing colors in gamma space, except this uses less instructions than a pow(x, 1/2.2)
	return sqrt(InColor);
}

/** Converts a linear input value into a value to be stored in the light attenuation buffer. */
half4 EncodeLightAttenuation(half4 InColor)
{
	return sqrt(InColor);
}

/** return the scene lighting texture */
half3 CalcSceneColor(float2 ScreenUV)
{
	return tex2D(SceneColorTexture,ScreenUV).rgb;
}

/** return all channels of the scene lighting texture */
half4 CalcFullSceneColor(float2 ScreenUV)
{
      return tex2D(SceneColorTexture,ScreenUV);
}

// Converts depth buffer Z / W into W
float ConvertFromDeviceZ(float DeviceZ)
{
	return 1.f / (DeviceZ * MinZ_MaxZRatio[2] - MinZ_MaxZRatio[3]);
}

/** Encodes the W coordinate of a pixel for storage in floating point. */
half EncodeFloatW(float W)
{
	#if SUPPORTS_DEPTH_TEXTURES
		return 0;
	#else
		float DepthAdd = MinZ_MaxZRatio[0];
		float DepthMul = MinZ_MaxZRatio[1];
		return DepthMul + DepthAdd / W;
	#endif
}

/** return the depth (half precision is ok) */
half GetSceneDeviceZ( float2 ScreenUV )
{
#if SUPPORTS_DEPTH_TEXTURES
	return texDepth2D(SceneDepthTexture, ScreenUV).r;
#else
	/** return the depth value stored in lighting target's alpha */
	return tex2Dlod(SceneColorTexture, float4(ScreenUV,0,0)).a;
#endif
}

/** Returns clip space W, which is world space distance along the View Z axis. */
float CalcSceneDepth( float2 ScreenUV )
{
	return ConvertFromDeviceZ(GetSceneDeviceZ(ScreenUV));
}

/**
* Returns scene color in rgb, depth in a
*/
float4 CalcSceneColorAndDepth( float2 ScreenUV )
{
	return float4(CalcSceneColor(ScreenUV), CalcSceneDepth(ScreenUV));
}

float PreviousDepth(float4 ScreenPosition)
{
	float2 ClipPos = float2(ScreenPosition.xy / ScreenPosition.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz);
	return CalcSceneDepth(ClipPos);
}

float PreviousDepth_FromMono(float4 ScreenPosition)
{
	float4 stereoClipPos = MonoToStereoClipPos(ScreenPosition);
	stereoClipPos.xy = float2(stereoClipPos.xy / stereoClipPos.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz);
	return CalcSceneDepth(stereoClipPos.xy);
}

#if SM5_PROFILE
	Texture2DMS<float> SceneDepthSurface;

	float CalcSceneDepthMSAA(float2 ScreenUV,uint SampleIndex)
	{
		float2 SurfaceDimensions;
		int NumSurfaceSamples;
		SceneDepthSurface.GetDimensions(SurfaceDimensions.x,SurfaceDimensions.y,NumSurfaceSamples);

		int2 IntUV = trunc(ScreenUV * SurfaceDimensions);
		float DeviceZ = SceneDepthSurface.Load(IntUV,SampleIndex);

		return ConvertFromDeviceZ(DeviceZ);
	}
	float PreviousDepthMSAA(float4 ScreenPosition,uint SampleIndex)
	{
		float4 stereoClipPos = MonoToStereoClipPos(ScreenPosition);
		stereoClipPos.xy = float2(stereoClipPos.xy / stereoClipPos.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz);
		return CalcSceneDepthMSAA(stereoClipPos.xy,SampleIndex);
	}
	float PreviousDepthForShadowsMSAA(float4 ScreenPosition,uint SampleIndex)
	{
		return PreviousDepthMSAA(ScreenPosition,SampleIndex);
	}
#endif

#if PS3
	float PreviousDepthForShadows(float4 ScreenPosition)
	{
		float2 ScreenUV = ScreenPosition.xy / ScreenPosition.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz;

		// get depth buffer z value
		float DeviceZ = texDepth2D(SceneDepthTexture,ScreenUV).r;

		// convert it to clip space w
		return ConvertFromDeviceZ(DeviceZ);
	}
#else
	float PreviousDepthForShadows(float4 ScreenPosition)
	{
		return PreviousDepth_FromMono(ScreenPosition);
	}
#endif

/** 
 * aligns the clip space position so that it can be used as a texture coordinate
 * to properly align in screen space
 */
float4 ScreenAlignedPosition( float4 ScreenPosition )
{
	return float4(ScreenPosition.xy / ScreenPosition.w * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz, ScreenPosition.z/ScreenPosition.w,1);
}

/** 
 * Aligns the [0,1] UV to match the view within the backbuffer
 */
half2 ScreenAlignedUV( half2 UV )
{
	return (UV*half2(2,-2) + half2(-1,1))*ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz;
}

/**
 * Calculate the normal Z component from X and Y
 */
float4 NormalCalcZ( float4 Normal )
{
	return float4( Normal.xy, sqrt(1.0 - dot(Normal.xy,Normal.xy)), 1 );
}
 
/*
 * Bias the normal sampled from a texture to the range of (-1..1, -1..1, -1..1, 0..1)
 */
float4 BiasNormalMap( float4 Normal )
{
	return Normal * float4(2.f,2.f,2.f,1.f) - float4(1.f,1.f,1.f,0.f);
}

#if PS3

float4 BiasNormalizeNormalMap_DXT1( float4 Normal ) { return Normal; }
float4 BiasNormalizeNormalMap_DXT5( float4 Normal ) { return BiasNormalMap(Normal); }
float4 BiasNormalizeNormalMap_V8U8( float4 Normal ) { return NormalCalcZ(Normal); }

#elif XBOX

// these cause problems with the Xbox shader compiler so we use a #define instead.
/*
float4 BiasNormalizeNormalMap_DXT1( float4 Normal ) { return BiasNormalMap(Normal); }
float4 BiasNormalizeNormalMap_DXT5( float4 Normal ) { return BiasNormalMap(Normal); }
float4 BiasNormalizeNormalMap_V8U8( float4 Normal ) { return NormalCalcZ(Normal); }
float4 BiasNormalizeNormalMap_BC5( float4 Normal ) { return NormalCalcZ(BiasNormalMap(Normal)); }
*/

#define NORMALCALCZ(Normal) (float4((Normal).xy, sqrt(1.f - dot((Normal).xy,(Normal).xy)), 1.f))
#define BIASNORMALMAP(Normal) ((Normal) * float4(2.f,2.f,2.f,1.f) - float4(1.f,1.f,1.f,0.f))

#define BiasNormalizeNormalMap_DXT1(Normal) BIASNORMALMAP(Normal)
#define BiasNormalizeNormalMap_DXT5(Normal) BIASNORMALMAP(Normal)
#define BiasNormalizeNormalMap_V8U8(Normal) NORMALCALCZ(Normal)
#define BiasNormalizeNormalMap_BC5(Normal) NORMALCALCZ(BIASNORMALMAP(Normal))

#else

float4 BiasNormalizeNormalMap_DXT1( float4 Normal ) { return BiasNormalMap(Normal); }
float4 BiasNormalizeNormalMap_DXT5( float4 Normal ) { return BiasNormalMap(Normal); }
float4 BiasNormalizeNormalMap_V8U8( float4 Normal ) { return NormalCalcZ(Normal); }
float4 BiasNormalizeNormalMap_BC5( float4 Normal ) { return NormalCalcZ(BiasNormalMap(Normal)); }

#endif

// Antialiased version of a binary comparison between ThresholdConst and a texture channel.
float AntialiasedTextureMask( sampler2D Tex, float2 UV, float ThresholdConst, int Channel )
{
	// By setting MaskConst to 0001, 0010, 0100 or 1000 individual channels can be chosen (the compiler should be able to optimize that).
	half4 MaskConst = half4(Channel == 0, Channel == 1, Channel == 2, Channel == 3);

	// border width in pixels, for antialiasing 1 .. 1.5 is good but 1.0 is good for optimizations 
	const float WidthConst = 1.0f;			
	float InvWidthConst = 1 / WidthConst;

	// Problem:

	// A simple texture lookup with a comparison against some thresold value allows to get a mask useful
	// for many purposes (e.g. text rendering, signs, oil/water/paint). Antialiased masks look much better
	// and mip mapping provides that but only for minification. So when the texture resolution is lower than
	// the rendering size results get blurry.

	// Idea:

	// We compute the distance to the threshold line in pixels (with subpixel precision). We can visualize
	// the problem as a heightmap that intersects a axis aligned plane at the threshold height. Only surface
	// above the threshold plane contributes to the mask. Looking at one pixel the heightmap can be approximated
	// by a plane. We can easily get the plane center value form a texture lookup and get the plane equation from
	// ddx and ddy of that value (only one value per 2x2 block) or some other more precise method. We can reduce the
	// 3d problem to 2d (looking at the steepest angle only) and the resulting value tells us how much the texture value
	// changes for one pixel. This allows us to scale and bias (threshold) the texture value the so it maps to the
	// distance function. We rescaling the distance to 0.5 coverage at the line, >1 half a pixel inside and <0 half
	// a pixel outside. Clamping this value in the range from 0..1 gives us a good approximation of the pixel coverage.

	// We tried multiple possible implementations - this is the cheapest and looks ok is most cases.
	// If quality improvements are needed we can add an option to the node later on.
	float Result;
	{
		// optimized, ddx/ddy only for every 2x2 block (bad for distant stuff)
		float Sample1 = dot(MaskConst, tex2D(Tex, UV));

		// compute the derivatives of the texture content
		float2 TexDD = float2(ddx(Sample1), ddy(Sample1));

		float TexDDLength = max(abs(TexDD.x), abs(TexDD.y)); 
		float Top = InvWidthConst * (Sample1 - ThresholdConst);
		Result = Top / TexDDLength + ThresholdConst;
	}

	Result = saturate(Result);	// no always needed (e.g. DX9 framebuffer blending)

	return Result;
}

//-----------------------------------------------
//@Rock - JoelS: Cheap pow
//-----------------------------------------------
// originally: pow(base, exponent) = x^y
// A and B are precomputed in code dependant on an error margin based off y as a constant with this basis:
// A	= ( pow( 0.5, ((y + 1.0f) / 2) ) - 1.0f ) / ( -0.5 )
// B	= 1.0 - A
// And then solved with:
// x^y	= max(0, A * x + B)^2

half3 computeCheapPow(half3 base, half2 expBasisAB)
{
	half3 t = abs( expBasisAB.x * base + expBasisAB.y );
	return t * t;
}

half computeCheapPow(half base, half2 expBasisAB)
{
	half t = abs( expBasisAB.x * base + expBasisAB.y );
	return t * t;
}

/*
* Clips a ray to an AABB.  Does not handle rays parallel to any of the planes.
*
* @param RayOrigin - The origin of the ray in world space.
* @param RayEnd - The end of the ray in world space.  
* @param BoxMin - The minimum extrema of the box.
* @param BoxMax - The maximum extrema of the box.
* @return - Returns the closest intersection along the ray in x, and furthest in y.  
*			If the ray did not intersect the box, then the furthest intersection <= the closest intersection.
*			The intersections will always be in the range [0,1], which corresponds to [RayOrigin, RayEnd] in worldspace.
*			To find the world space position of either intersection, simply plug it back into the ray equation:
*			WorldPos = RayOrigin + (RayEnd - RayOrigin) * Intersection;
*/
float2 RayBoxIntersect(float3 RayOrigin, float3 RayEnd, float3 BoxMin, float3 BoxMax)
{
	float3 InvRayDir = 1.0f / (RayEnd - RayOrigin);
	
	//find the ray intersection with each of the 3 planes defined by the minimum extrema.
	float3 FirstPlaneIntersections = (BoxMin - RayOrigin) * InvRayDir;
	//find the ray intersection with each of the 3 planes defined by the maximum extrema.
	float3 SecondPlaneIntersections = (BoxMax - RayOrigin) * InvRayDir;
	//get the closest of these intersections along the ray
	float3 ClosestPlaneIntersections = min(FirstPlaneIntersections, SecondPlaneIntersections);
	//get the furthest of these intersections along the ray
	float3 FurthestPlaneIntersections = max(FirstPlaneIntersections, SecondPlaneIntersections);

	float2 BoxIntersections;
	//find the furthest near intersection
	BoxIntersections.x = max(ClosestPlaneIntersections.x, max(ClosestPlaneIntersections.y, ClosestPlaneIntersections.z));
	//find the closest far intersection
	BoxIntersections.y = min(FurthestPlaneIntersections.x, min(FurthestPlaneIntersections.y, FurthestPlaneIntersections.z));
	//clamp the intersections to be between RayOrigin and RayEnd on the ray
	return saturate(BoxIntersections);
}

/** Transforms a vector from tangent space to world space */
float3 TransformTangentVectorToWorld(float3x3 TangentToWorld, float3 InTangentVector)
{
	// Transform directly to world space
	// The vector transform is optimized for this case, only one vector-matrix multiply is needed
	return mul(TangentToWorld, InTangentVector);
}

/** Transforms a vector from world space to tangent space */
float3 TransformWorldVectorToTangent(float3x3 TangentToWorld, float3 InWorldVector)
{
	// Transform from world to tangent space
	return mul(InWorldVector, TangentToWorld);
}

/** Applies the temporal AA jitter to a screen-space position. */
float4 ApplyTemporalAAJitter(float4 ScreenPosition,float4 TemporalAAParameters)
{
	float2 Offset = TemporalAAParameters.xy;
	float StartDepth = TemporalAAParameters.z;

	float Depth = ScreenPosition.w;
	float Factor = Depth > StartDepth ? 1 : 0;

	return float4(
		ScreenPosition.xy + Factor * Depth * Offset,
		ScreenPosition.zw
		);
}

// Define passthrough implementations of EvaluateAttributeAtSample for non-D3D11 platforms.
#if PS3
	typedef unsigned int uint;
#endif

#if !SM5_PROFILE
	float EvaluateAttributeAtSample(float Attribute,uint SampleIndex) { return Attribute; }
	float2 EvaluateAttributeAtSample(float2 Attribute,uint SampleIndex) { return Attribute; }
	float3 EvaluateAttributeAtSample(float3 Attribute,uint SampleIndex) { return Attribute; }
	float4 EvaluateAttributeAtSample(float4 Attribute,uint SampleIndex) { return Attribute; }
#endif


#if !XBOX
// for XBOX the function is implemented in XBox360Common
half4 FixupSceneColor(half4 In)
{
	return In;
}
#endif


/** same as GSceneRenderTargets.bSceneColorTextureIsRaw */
bool bDecompressSceneColor;

half4 GetMaterialEffectSceneColor(sampler2D s, float2 UV)
{
	half4 SceneColor = tex2D(s, UV);

#if XBOX
	// static branch
	if(bDecompressSceneColor)
	{
		// if the SceneColor is in RAW we need to decompress it
		// this means it's before tone mapping
		SceneColor = FixupSceneColor(SceneColor); 
	}
#endif

	return SceneColor;
}
