/*=============================================================================
	RockAtmosVertexShader.usf:
=============================================================================*/
#include "Common.usf"

float4x4 ScreenToWorld;

void Main(		float2 InPosition				: POSITION,
				/* float2 InScreenUV				: TEXCOORD0, */ // NVCHANGE_RS: JJ - DX10/11 stricter about linkage, including unused inputs

				out float4 OutScreenPosition	: TEXCOORD0,
				out float3 OutScreenVector		: TEXCOORD1,
				out float4 OutPosition			: POSITION		)
{
	// screenspace position from vb
	OutPosition = float4(InPosition,0,1);
	// texture coord from vb
	OutScreenPosition.xy = InPosition;
	OutScreenPosition.zw = InPosition * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz;

	// deproject to world space
	OutScreenVector = MulMatrix(ScreenToWorld,float4(InPosition,1,0)); 
} 